# MongoDB Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: todo-lab
  labels:
    app: mongodb
    env: dev
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=                  # Base64: admin
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=          # Base64: password123
